using System.Globalization;
using StartOpenClawLauncher.Models;

namespace StartOpenClawLauncher.Services;

public sealed class LocalizationService
{
    private readonly Dictionary<string, Dictionary<string, string>> _translations;
    private readonly Dictionary<string, LanguageOption> _languageMap;

    public LocalizationService()
    {
        Languages =
        [
            new LanguageOption { Code = "en", DisplayName = "English" },
            new LanguageOption { Code = "zh-CN", DisplayName = "中文" },
            new LanguageOption { Code = "hi", DisplayName = "हिन्दी" },
            new LanguageOption { Code = "es", DisplayName = "Español" },
            new LanguageOption { Code = "ar", DisplayName = "العربية" },
            new LanguageOption { Code = "ru", DisplayName = "Русский" },
            new LanguageOption { Code = "pt", DisplayName = "Português" },
            new LanguageOption { Code = "fr", DisplayName = "Français" },
            new LanguageOption { Code = "it", DisplayName = "Italiano" },
            new LanguageOption { Code = "ja", DisplayName = "日本語" }
        ];

        _languageMap = Languages.ToDictionary(language => language.Code, StringComparer.OrdinalIgnoreCase);
        _translations = BuildTranslations();
        CurrentLanguage = "en";
    }

    public IReadOnlyList<LanguageOption> Languages { get; }

    public string CurrentLanguage { get; private set; }

    public void SetLanguage(string? code)
    {
        var normalized = string.IsNullOrWhiteSpace(code) ? "en" : code.Trim();
        if (!_languageMap.ContainsKey(normalized))
        {
            normalized = "en";
        }

        CurrentLanguage = normalized;
    }

    public string T(string key, params object[] arguments)
    {
        var template = TryGet(CurrentLanguage, key)
            ?? TryGet("en", key)
            ?? key;

        return arguments.Length == 0
            ? template
            : string.Format(CultureInfo.InvariantCulture, template, arguments);
    }

    private string? TryGet(string languageCode, string key)
    {
        return _translations.TryGetValue(languageCode, out var table) && table.TryGetValue(key, out var value)
            ? value
            : null;
    }

    private static Dictionary<string, Dictionary<string, string>> BuildTranslations()
    {
        return new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderSubtitle"] = "Start Clash (if installed) and OpenClaw with one click, and stop OpenClaw with one click.",
                ["LanguageLabel"] = "Language",
                ["CardClash"] = "Clash Status",
                ["CardProxy"] = "Proxy Status",
                ["CardOpenClaw"] = "OpenClaw Status",
                ["ButtonStart"] = "Start OpenClaw",
                ["ButtonStop"] = "Stop OpenClaw",
                ["HintBusy"] = "Working, please wait...",
                ["HintIdle"] = "The start button checks Clash first, then OpenClaw; if OpenClaw is missing, the official install page opens.",
                ["CardAccess"] = "Access URL",
                ["AccessDescription"] = "When OpenClaw is confirmed running, this URL opens automatically in your browser.",
                ["CardRuntime"] = "Runtime Duration",
                ["RuntimeIdleDescription"] = "The timer starts automatically after launch.",
                ["LogsTitle"] = "Runtime Logs",
                ["Checking"] = "Checking...",
                ["InstalledRunning"] = "Installed / Running",
                ["InstalledNotRunning"] = "Installed / Not running",
                ["NotDetected"] = "Not detected",
                ["DetectedPathUnknown"] = "Detected, but the path is unknown.",
                ["ClashMissingDetail"] = "Clash was not found in common paths, running processes, or the registry.",
                ["ProxyReady"] = "Proxy ready",
                ["ProxyReadySystemEnabled"] = "Proxy ready / System proxy enabled",
                ["ProxyReadySystemDisabled"] = "Proxy ready / System proxy disabled",
                ["ProxyNotReady"] = "Proxy not ready",
                ["SystemProxyEnabled"] = "Enabled",
                ["SystemProxyDisabled"] = "Disabled",
                ["ProxyDetail"] = "Endpoint: {0}:{1} | System proxy: {2}",
                ["OpenClawMissingDetail"] = "OpenClaw was not found in PATH or common global npm locations.",
                ["OpenClawPathDetail"] = "Path: {0}{1}",
                ["RuntimeUnknown"] = "Running (start time unavailable)",
                ["RuntimeUnknownDetail"] = "This process may not have been started by this launcher, so the full runtime cannot be calculated.",
                ["RuntimeStartedAt"] = "Started at: {0}",
                ["RuntimeLastRun"] = "Last run: {0}",
                ["RuntimeNotRunning"] = "Not running",
                ["RuntimeStoppedDetail"] = "OpenClaw is not currently running.",
                ["ReadyLog"] = "Launcher is ready. The config file is located next to the executable as config.json.",
                ["StartFlowLog"] = "Starting the one-click startup flow...",
                ["StopFlowLog"] = "Starting the one-click shutdown flow...",
                ["UnhandledException"] = "Unhandled exception: {0}",
                ["NotInstalledMessage"] = "OpenClaw was not detected. The official install page will open next.",
                ["InfoTitle"] = "Info",
                ["ErrorTitle"] = "Error",
                ["OpeningUrlLog"] = "Opening OpenClaw access URL: {0}",
                ["ErrorPrefix"] = "[Error] ",
                ["ClashRunningDetectedLog"] = "Clash is already running.",
                ["ClashDetectedLog"] = "Clash detected: {0}",
                ["ClashStartAttemptLog"] = "Attempted to start Clash. Waiting for the proxy port to become available...",
                ["ProxyReadyLog"] = "Proxy port {0}:{1} is ready.",
                ["SystemProxyAlreadyLog"] = "System proxy already points to {0}. No change needed.",
                ["SystemProxyEnabledLog"] = "System proxy has been enabled: {0}",
                ["SystemProxyEnableFailedLog"] = "The proxy port was detected, but automatic system proxy enablement failed. Please check your Windows proxy settings manually.",
                ["ProxyNotReadyLog"] = "Warning: Clash was detected, but proxy port {0}:{1} is not ready yet. Automatic system proxy enablement was skipped.",
                ["ClashNotDetectedLog"] = "Clash was not detected. Continuing without a proxy.",
                ["OpenClawMissingSummary"] = "OpenClaw was not detected. The official install page is ready to open.",
                ["OpenClawRunningReadySummary"] = "OpenClaw is already running (PID: {0}). The access URL will open automatically.",
                ["OpenClawRunningNotReadySummary"] = "OpenClaw is already running (PID: {0}), but the access URL is not ready yet.",
                ["SuspectedProcessLog"] = "A suspected OpenClaw process was detected (PID: {0}), but the gateway port is not ready. A restart attempt will continue.",
                ["OpenClawCreateFailedSummary"] = "OpenClaw failed to start because the process could not be created.",
                ["OpenClawStartedSummary"] = "OpenClaw has started. Access URL: {0}",
                ["OpenClawStartedNotReadySummary"] = "An OpenClaw process was started (PID: {0}), but the access port was not detected within the timeout.",
                ["DaemonStopLog"] = "Tried to stop OpenClaw by running 'daemon stop'.",
                ["KillRecordedPidLog"] = "Stopping the OpenClaw process recorded by the launcher (PID: {0}).",
                ["KillPortPidLog"] = "Stopping the OpenClaw process listening on port {0} (PID: {1}).",
                ["KillGatewayPidLog"] = "Stopping a matched OpenClaw gateway process (PID: {0}).",
                ["OpenClawStoppedSummary"] = "OpenClaw has stopped.",
                ["OpenClawStoppedDurationSummary"] = "OpenClaw has stopped. This session ran for {0}.",
                ["OpenClawStopNotConfirmedSummary"] = "Could not confirm that OpenClaw stopped completely. Please review the logs."
            },
            ["zh-CN"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw 桌面启动器",
                ["HeaderTitle"] = "OpenClaw 桌面启动器",
                ["HeaderSubtitle"] = "一键启动 Clash（如已安装）与 OpenClaw，并支持一键关闭 OpenClaw。",
                ["LanguageLabel"] = "语言",
                ["CardClash"] = "Clash 状态",
                ["CardProxy"] = "代理状态",
                ["CardOpenClaw"] = "OpenClaw 状态",
                ["ButtonStart"] = "启动 OpenClaw",
                ["ButtonStop"] = "关闭 OpenClaw",
                ["HintBusy"] = "正在执行，请稍候...",
                ["HintIdle"] = "启动按钮会先检查 Clash，再检查 OpenClaw；若未检测到 OpenClaw，将打开官方安装页面。",
                ["CardAccess"] = "访问地址",
                ["AccessDescription"] = "当确认 OpenClaw 已运行时，此地址会自动在浏览器中打开。",
                ["CardRuntime"] = "运行时长",
                ["RuntimeIdleDescription"] = "启动后将自动开始计时。",
                ["LogsTitle"] = "运行日志",
                ["Checking"] = "检测中...",
                ["InstalledRunning"] = "已安装 / 运行中",
                ["InstalledNotRunning"] = "已安装 / 未运行",
                ["NotDetected"] = "未检测到",
                ["DetectedPathUnknown"] = "已检测到，但路径未知。",
                ["ClashMissingDetail"] = "未在常见路径、运行进程或注册表中检测到 Clash。",
                ["ProxyReady"] = "代理可用",
                ["ProxyReadySystemEnabled"] = "代理可用 / 系统代理已开启",
                ["ProxyReadySystemDisabled"] = "代理可用 / 系统代理未开启",
                ["ProxyNotReady"] = "代理未就绪",
                ["SystemProxyEnabled"] = "已开启",
                ["SystemProxyDisabled"] = "未开启",
                ["ProxyDetail"] = "地址：{0}:{1} | 系统代理：{2}",
                ["OpenClawMissingDetail"] = "未在 PATH 或常见全局 npm 目录中检测到 OpenClaw。",
                ["OpenClawPathDetail"] = "路径：{0}{1}",
                ["RuntimeUnknown"] = "正在运行（启动时间未知）",
                ["RuntimeUnknownDetail"] = "该进程可能不是由此启动器拉起，因此无法精确统计完整时长。",
                ["RuntimeStartedAt"] = "启动时间：{0}",
                ["RuntimeLastRun"] = "上次运行：{0}",
                ["RuntimeNotRunning"] = "未运行",
                ["RuntimeStoppedDetail"] = "OpenClaw 当前未运行。",
                ["ReadyLog"] = "启动器已就绪。配置文件位于可执行文件同目录下的 config.json。",
                ["StartFlowLog"] = "开始执行一键启动流程...",
                ["StopFlowLog"] = "开始执行一键关闭流程...",
                ["UnhandledException"] = "发生未处理异常：{0}",
                ["NotInstalledMessage"] = "未检测到 OpenClaw，接下来会打开官方安装页面。",
                ["InfoTitle"] = "提示",
                ["ErrorTitle"] = "错误",
                ["OpeningUrlLog"] = "正在打开 OpenClaw 访问地址：{0}",
                ["ErrorPrefix"] = "[错误] ",
                ["ClashRunningDetectedLog"] = "已检测到 Clash 正在运行。",
                ["ClashDetectedLog"] = "检测到 Clash：{0}",
                ["ClashStartAttemptLog"] = "已尝试启动 Clash，正在等待代理端口就绪...",
                ["ProxyReadyLog"] = "代理端口 {0}:{1} 已就绪。",
                ["SystemProxyAlreadyLog"] = "系统代理已指向 {0}，无需重复开启。",
                ["SystemProxyEnabledLog"] = "已自动开启系统代理：{0}",
                ["SystemProxyEnableFailedLog"] = "已检测到代理端口，但自动开启系统代理失败，请手动检查 Windows 代理设置。",
                ["ProxyNotReadyLog"] = "警告：已检测到 Clash，但代理端口 {0}:{1} 尚未就绪，已跳过自动开启系统代理。",
                ["ClashNotDetectedLog"] = "未检测到 Clash，将按无代理模式继续。",
                ["OpenClawMissingSummary"] = "未检测到 OpenClaw，已准备打开官方安装页面。",
                ["OpenClawRunningReadySummary"] = "OpenClaw 已在运行中（PID: {0}），将自动打开访问地址。",
                ["OpenClawRunningNotReadySummary"] = "OpenClaw 已在运行中（PID: {0}），但访问地址暂未就绪。",
                ["SuspectedProcessLog"] = "检测到疑似 OpenClaw 进程（PID: {0}），但网关端口未就绪，将继续尝试重启。",
                ["OpenClawCreateFailedSummary"] = "OpenClaw 启动失败，未能创建进程。",
                ["OpenClawStartedSummary"] = "OpenClaw 已启动，访问地址：{0}",
                ["OpenClawStartedNotReadySummary"] = "已启动 OpenClaw 进程（PID: {0}），但在超时时间内未检测到访问端口。",
                ["DaemonStopLog"] = "已尝试通过 daemon stop 关闭 OpenClaw。",
                ["KillRecordedPidLog"] = "正在结束由启动器记录的 OpenClaw 进程（PID: {0}）。",
                ["KillPortPidLog"] = "正在结束监听端口 {0} 的 OpenClaw 进程（PID: {1}）。",
                ["KillGatewayPidLog"] = "正在结束匹配到的 OpenClaw 网关进程（PID: {0}）。",
                ["OpenClawStoppedSummary"] = "OpenClaw 已关闭。",
                ["OpenClawStoppedDurationSummary"] = "OpenClaw 已关闭，本次运行时长：{0}。",
                ["OpenClawStopNotConfirmedSummary"] = "未能确认 OpenClaw 已完全关闭，请查看日志继续排查。"
            },
            ["hi"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderSubtitle"] = "एक क्लिक में Clash (यदि इंस्टॉल है) और OpenClaw शुरू करें, और एक क्लिक में OpenClaw बंद करें।",
                ["LanguageLabel"] = "भाषा",
                ["CardClash"] = "Clash स्थिति",
                ["CardProxy"] = "प्रॉक्सी स्थिति",
                ["CardOpenClaw"] = "OpenClaw स्थिति",
                ["ButtonStart"] = "OpenClaw शुरू करें",
                ["ButtonStop"] = "OpenClaw बंद करें",
                ["HintBusy"] = "कृपया प्रतीक्षा करें...",
                ["HintIdle"] = "स्टार्ट बटन पहले Clash और फिर OpenClaw की जांच करता है; यदि OpenClaw नहीं मिलता, तो आधिकारिक इंस्टॉल पेज खुलेगा।",
                ["CardAccess"] = "एक्सेस URL",
                ["AccessDescription"] = "जब OpenClaw चल रहा होगा, यह URL अपने आप ब्राउज़र में खुलेगा।",
                ["CardRuntime"] = "चलने की अवधि",
                ["RuntimeIdleDescription"] = "शुरू होने के बाद टाइमर अपने आप शुरू होगा।",
                ["LogsTitle"] = "रनटाइम लॉग",
                ["Checking"] = "जांच हो रही है...",
                ["InstalledRunning"] = "इंस्टॉल / चल रहा है",
                ["InstalledNotRunning"] = "इंस्टॉल / नहीं चल रहा",
                ["NotDetected"] = "नहीं मिला",
                ["DetectedPathUnknown"] = "मिल गया, लेकिन पथ अज्ञात है।",
                ["ClashMissingDetail"] = "सामान्य पथों, प्रक्रियाओं या रजिस्ट्री में Clash नहीं मिला।",
                ["ProxyReady"] = "प्रॉक्सी तैयार",
                ["ProxyReadySystemEnabled"] = "प्रॉक्सी तैयार / सिस्टम प्रॉक्सी सक्षम",
                ["ProxyReadySystemDisabled"] = "प्रॉक्सी तैयार / सिस्टम प्रॉक्सी अक्षम",
                ["ProxyNotReady"] = "प्रॉक्सी तैयार नहीं",
                ["SystemProxyEnabled"] = "सक्षम",
                ["SystemProxyDisabled"] = "अक्षम",
                ["ProxyDetail"] = "एंडपॉइंट: {0}:{1} | सिस्टम प्रॉक्सी: {2}",
                ["OpenClawMissingDetail"] = "PATH या सामान्य global npm स्थानों में OpenClaw नहीं मिला।",
                ["OpenClawPathDetail"] = "पथ: {0}{1}",
                ["RuntimeUnknown"] = "चल रहा है (शुरुआती समय उपलब्ध नहीं)",
                ["RuntimeUnknownDetail"] = "संभव है यह प्रक्रिया इस लॉन्चर द्वारा शुरू नहीं की गई हो।",
                ["RuntimeStartedAt"] = "शुरुआत का समय: {0}",
                ["RuntimeLastRun"] = "पिछली अवधि: {0}",
                ["RuntimeNotRunning"] = "नहीं चल रहा",
                ["RuntimeStoppedDetail"] = "OpenClaw अभी नहीं चल रहा है।",
                ["InfoTitle"] = "जानकारी",
                ["ErrorTitle"] = "त्रुटि",
                ["ErrorPrefix"] = "[त्रुटि] "
            },
            ["es"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderSubtitle"] = "Inicia Clash (si está instalado) y OpenClaw con un clic, y detén OpenClaw con un clic.",
                ["LanguageLabel"] = "Idioma",
                ["CardClash"] = "Estado de Clash",
                ["CardProxy"] = "Estado del proxy",
                ["CardOpenClaw"] = "Estado de OpenClaw",
                ["ButtonStart"] = "Iniciar OpenClaw",
                ["ButtonStop"] = "Detener OpenClaw",
                ["HintBusy"] = "Trabajando, por favor espera...",
                ["HintIdle"] = "El botón de inicio comprueba primero Clash y luego OpenClaw; si OpenClaw no existe, se abrirá la página oficial de instalación.",
                ["CardAccess"] = "URL de acceso",
                ["AccessDescription"] = "Cuando OpenClaw esté ejecutándose, esta URL se abrirá automáticamente en tu navegador.",
                ["CardRuntime"] = "Tiempo de ejecución",
                ["RuntimeIdleDescription"] = "El temporizador comienza automáticamente después del inicio.",
                ["LogsTitle"] = "Registros de ejecución",
                ["Checking"] = "Comprobando...",
                ["InstalledRunning"] = "Instalado / En ejecución",
                ["InstalledNotRunning"] = "Instalado / Detenido",
                ["NotDetected"] = "No detectado",
                ["DetectedPathUnknown"] = "Detectado, pero la ruta es desconocida.",
                ["ClashMissingDetail"] = "Clash no se encontró en rutas comunes, procesos o registro.",
                ["ProxyReady"] = "Proxy listo",
                ["ProxyReadySystemEnabled"] = "Proxy listo / Proxy del sistema activado",
                ["ProxyReadySystemDisabled"] = "Proxy listo / Proxy del sistema desactivado",
                ["ProxyNotReady"] = "Proxy no listo",
                ["SystemProxyEnabled"] = "Activado",
                ["SystemProxyDisabled"] = "Desactivado",
                ["ProxyDetail"] = "Extremo: {0}:{1} | Proxy del sistema: {2}",
                ["OpenClawMissingDetail"] = "OpenClaw no se encontró en PATH o ubicaciones globales comunes de npm.",
                ["OpenClawPathDetail"] = "Ruta: {0}{1}",
                ["RuntimeUnknown"] = "En ejecución (hora de inicio no disponible)",
                ["RuntimeUnknownDetail"] = "Es posible que este proceso no haya sido iniciado por este lanzador.",
                ["RuntimeStartedAt"] = "Iniciado a las: {0}",
                ["RuntimeLastRun"] = "Última ejecución: {0}",
                ["RuntimeNotRunning"] = "No está en ejecución",
                ["RuntimeStoppedDetail"] = "OpenClaw no se está ejecutando actualmente.",
                ["InfoTitle"] = "Información",
                ["ErrorTitle"] = "Error",
                ["ErrorPrefix"] = "[Error] "
            },
            ["ar"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderSubtitle"] = "ابدأ Clash (إذا كان مثبتًا) وOpenClaw بنقرة واحدة، وأوقف OpenClaw بنقرة واحدة.",
                ["LanguageLabel"] = "اللغة",
                ["CardClash"] = "حالة Clash",
                ["CardProxy"] = "حالة الوكيل",
                ["CardOpenClaw"] = "حالة OpenClaw",
                ["ButtonStart"] = "بدء OpenClaw",
                ["ButtonStop"] = "إيقاف OpenClaw",
                ["HintBusy"] = "جارٍ التنفيذ، يرجى الانتظار...",
                ["HintIdle"] = "يفحص زر البدء Clash أولاً ثم OpenClaw؛ وإذا لم يتم العثور على OpenClaw فستُفتح صفحة التثبيت الرسمية.",
                ["CardAccess"] = "رابط الوصول",
                ["AccessDescription"] = "عند التأكد من تشغيل OpenClaw، سيتم فتح هذا الرابط تلقائيًا في المتصفح.",
                ["CardRuntime"] = "مدة التشغيل",
                ["RuntimeIdleDescription"] = "يبدأ المؤقت تلقائيًا بعد التشغيل.",
                ["LogsTitle"] = "سجلات التشغيل",
                ["Checking"] = "جارٍ الفحص...",
                ["InstalledRunning"] = "مثبت / قيد التشغيل",
                ["InstalledNotRunning"] = "مثبت / غير قيد التشغيل",
                ["NotDetected"] = "غير مكتشف",
                ["DetectedPathUnknown"] = "تم الاكتشاف، لكن المسار غير معروف.",
                ["ClashMissingDetail"] = "لم يتم العثور على Clash في المسارات الشائعة أو العمليات أو السجل.",
                ["ProxyReady"] = "الوكيل جاهز",
                ["ProxyReadySystemEnabled"] = "الوكيل جاهز / وكيل النظام مفعّل",
                ["ProxyReadySystemDisabled"] = "الوكيل جاهز / وكيل النظام غير مفعّل",
                ["ProxyNotReady"] = "الوكيل غير جاهز",
                ["SystemProxyEnabled"] = "مفعّل",
                ["SystemProxyDisabled"] = "غير مفعّل",
                ["ProxyDetail"] = "العنوان: {0}:{1} | وكيل النظام: {2}",
                ["OpenClawMissingDetail"] = "لم يتم العثور على OpenClaw في PATH أو في مواقع npm الشائعة.",
                ["OpenClawPathDetail"] = "المسار: {0}{1}",
                ["RuntimeUnknown"] = "قيد التشغيل (وقت البدء غير متاح)",
                ["RuntimeUnknownDetail"] = "قد لا تكون هذه العملية قد بدأت بواسطة هذا المشغّل.",
                ["RuntimeStartedAt"] = "وقت البدء: {0}",
                ["RuntimeLastRun"] = "آخر تشغيل: {0}",
                ["RuntimeNotRunning"] = "غير قيد التشغيل",
                ["RuntimeStoppedDetail"] = "OpenClaw غير قيد التشغيل حاليًا.",
                ["InfoTitle"] = "معلومات",
                ["ErrorTitle"] = "خطأ",
                ["ErrorPrefix"] = "[خطأ] "
            },
            ["ru"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderSubtitle"] = "Запускайте Clash (если установлен) и OpenClaw одним нажатием и останавливайте OpenClaw одним нажатием.",
                ["LanguageLabel"] = "Язык",
                ["CardClash"] = "Статус Clash",
                ["CardProxy"] = "Статус прокси",
                ["CardOpenClaw"] = "Статус OpenClaw",
                ["ButtonStart"] = "Запустить OpenClaw",
                ["ButtonStop"] = "Остановить OpenClaw",
                ["HintBusy"] = "Выполняется, пожалуйста подождите...",
                ["HintIdle"] = "Кнопка запуска сначала проверяет Clash, затем OpenClaw; если OpenClaw не найден, откроется официальная страница установки.",
                ["CardAccess"] = "URL доступа",
                ["AccessDescription"] = "Когда работа OpenClaw подтверждена, этот URL автоматически откроется в браузере.",
                ["CardRuntime"] = "Время работы",
                ["RuntimeIdleDescription"] = "Таймер запускается автоматически после старта.",
                ["LogsTitle"] = "Журнал выполнения",
                ["Checking"] = "Проверка...",
                ["InstalledRunning"] = "Установлен / Запущен",
                ["InstalledNotRunning"] = "Установлен / Не запущен",
                ["NotDetected"] = "Не обнаружен",
                ["DetectedPathUnknown"] = "Обнаружен, но путь неизвестен.",
                ["ClashMissingDetail"] = "Clash не найден в типовых путях, процессах или реестре.",
                ["ProxyReady"] = "Прокси готов",
                ["ProxyReadySystemEnabled"] = "Прокси готов / Системный прокси включен",
                ["ProxyReadySystemDisabled"] = "Прокси готов / Системный прокси выключен",
                ["ProxyNotReady"] = "Прокси не готов",
                ["SystemProxyEnabled"] = "Включен",
                ["SystemProxyDisabled"] = "Выключен",
                ["ProxyDetail"] = "Адрес: {0}:{1} | Системный прокси: {2}",
                ["OpenClawMissingDetail"] = "OpenClaw не найден в PATH или типовых глобальных каталогах npm.",
                ["OpenClawPathDetail"] = "Путь: {0}{1}",
                ["RuntimeUnknown"] = "Запущен (время старта недоступно)",
                ["RuntimeUnknownDetail"] = "Возможно, этот процесс был запущен не этим лаунчером.",
                ["RuntimeStartedAt"] = "Время запуска: {0}",
                ["RuntimeLastRun"] = "Последний запуск: {0}",
                ["RuntimeNotRunning"] = "Не запущен",
                ["RuntimeStoppedDetail"] = "OpenClaw сейчас не запущен.",
                ["InfoTitle"] = "Информация",
                ["ErrorTitle"] = "Ошибка",
                ["ErrorPrefix"] = "[Ошибка] "
            },
            ["pt"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderSubtitle"] = "Inicie o Clash (se instalado) e o OpenClaw com um clique, e encerre o OpenClaw com um clique.",
                ["LanguageLabel"] = "Idioma",
                ["CardClash"] = "Status do Clash",
                ["CardProxy"] = "Status do proxy",
                ["CardOpenClaw"] = "Status do OpenClaw",
                ["ButtonStart"] = "Iniciar OpenClaw",
                ["ButtonStop"] = "Parar OpenClaw",
                ["HintBusy"] = "Processando, aguarde...",
                ["HintIdle"] = "O botão iniciar verifica primeiro o Clash e depois o OpenClaw; se o OpenClaw não for encontrado, a página oficial será aberta.",
                ["CardAccess"] = "URL de acesso",
                ["AccessDescription"] = "Quando o OpenClaw estiver confirmado em execução, esta URL será aberta automaticamente no navegador.",
                ["CardRuntime"] = "Tempo de execução",
                ["RuntimeIdleDescription"] = "O cronômetro começa automaticamente após a inicialização.",
                ["LogsTitle"] = "Logs de execução",
                ["Checking"] = "Verificando...",
                ["InstalledRunning"] = "Instalado / Em execução",
                ["InstalledNotRunning"] = "Instalado / Parado",
                ["NotDetected"] = "Não detectado",
                ["DetectedPathUnknown"] = "Detectado, mas o caminho é desconhecido.",
                ["ClashMissingDetail"] = "O Clash não foi encontrado em caminhos comuns, processos ou registro.",
                ["ProxyReady"] = "Proxy pronto",
                ["ProxyReadySystemEnabled"] = "Proxy pronto / Proxy do sistema ativado",
                ["ProxyReadySystemDisabled"] = "Proxy pronto / Proxy do sistema desativado",
                ["ProxyNotReady"] = "Proxy não pronto",
                ["SystemProxyEnabled"] = "Ativado",
                ["SystemProxyDisabled"] = "Desativado",
                ["ProxyDetail"] = "Endereço: {0}:{1} | Proxy do sistema: {2}",
                ["OpenClawMissingDetail"] = "O OpenClaw não foi encontrado no PATH ou em locais globais comuns do npm.",
                ["OpenClawPathDetail"] = "Caminho: {0}{1}",
                ["RuntimeUnknown"] = "Em execução (hora de início indisponível)",
                ["RuntimeUnknownDetail"] = "Este processo pode não ter sido iniciado por este launcher.",
                ["RuntimeStartedAt"] = "Iniciado em: {0}",
                ["RuntimeLastRun"] = "Última execução: {0}",
                ["RuntimeNotRunning"] = "Não está em execução",
                ["RuntimeStoppedDetail"] = "O OpenClaw não está em execução no momento.",
                ["InfoTitle"] = "Informação",
                ["ErrorTitle"] = "Erro",
                ["ErrorPrefix"] = "[Erro] "
            },
            ["fr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderSubtitle"] = "Lancez Clash (s'il est installé) et OpenClaw en un clic, puis arrêtez OpenClaw en un clic.",
                ["LanguageLabel"] = "Langue",
                ["CardClash"] = "État de Clash",
                ["CardProxy"] = "État du proxy",
                ["CardOpenClaw"] = "État d'OpenClaw",
                ["ButtonStart"] = "Démarrer OpenClaw",
                ["ButtonStop"] = "Arrêter OpenClaw",
                ["HintBusy"] = "Traitement en cours, veuillez patienter...",
                ["HintIdle"] = "Le bouton de démarrage vérifie d'abord Clash puis OpenClaw ; si OpenClaw est introuvable, la page officielle s'ouvrira.",
                ["CardAccess"] = "URL d'accès",
                ["AccessDescription"] = "Lorsque le fonctionnement d'OpenClaw est confirmé, cette URL s'ouvre automatiquement dans le navigateur.",
                ["CardRuntime"] = "Durée d'exécution",
                ["RuntimeIdleDescription"] = "Le minuteur démarre automatiquement après le lancement.",
                ["LogsTitle"] = "Journaux d'exécution",
                ["Checking"] = "Vérification...",
                ["InstalledRunning"] = "Installé / En cours",
                ["InstalledNotRunning"] = "Installé / Arrêté",
                ["NotDetected"] = "Non détecté",
                ["DetectedPathUnknown"] = "Détecté, mais le chemin est inconnu.",
                ["ClashMissingDetail"] = "Clash est introuvable dans les chemins courants, les processus ou le registre.",
                ["ProxyReady"] = "Proxy prêt",
                ["ProxyReadySystemEnabled"] = "Proxy prêt / Proxy système activé",
                ["ProxyReadySystemDisabled"] = "Proxy prêt / Proxy système désactivé",
                ["ProxyNotReady"] = "Proxy non prêt",
                ["SystemProxyEnabled"] = "Activé",
                ["SystemProxyDisabled"] = "Désactivé",
                ["ProxyDetail"] = "Adresse : {0}:{1} | Proxy système : {2}",
                ["OpenClawMissingDetail"] = "OpenClaw est introuvable dans PATH ou dans les emplacements npm courants.",
                ["OpenClawPathDetail"] = "Chemin : {0}{1}",
                ["RuntimeUnknown"] = "En cours (heure de démarrage indisponible)",
                ["RuntimeUnknownDetail"] = "Ce processus n'a peut-être pas été lancé par ce lanceur.",
                ["RuntimeStartedAt"] = "Démarré à : {0}",
                ["RuntimeLastRun"] = "Dernière exécution : {0}",
                ["RuntimeNotRunning"] = "Non en cours",
                ["RuntimeStoppedDetail"] = "OpenClaw n'est pas en cours d'exécution actuellement.",
                ["InfoTitle"] = "Information",
                ["ErrorTitle"] = "Erreur",
                ["ErrorPrefix"] = "[Erreur] "
            },
            ["it"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderSubtitle"] = "Avvia Clash (se installato) e OpenClaw con un clic e arresta OpenClaw con un clic.",
                ["LanguageLabel"] = "Lingua",
                ["CardClash"] = "Stato di Clash",
                ["CardProxy"] = "Stato del proxy",
                ["CardOpenClaw"] = "Stato di OpenClaw",
                ["ButtonStart"] = "Avvia OpenClaw",
                ["ButtonStop"] = "Arresta OpenClaw",
                ["HintBusy"] = "Operazione in corso, attendere...",
                ["HintIdle"] = "Il pulsante di avvio controlla prima Clash e poi OpenClaw; se OpenClaw non viene trovato, si aprirà la pagina ufficiale.",
                ["CardAccess"] = "URL di accesso",
                ["AccessDescription"] = "Quando OpenClaw risulta in esecuzione, questo URL viene aperto automaticamente nel browser.",
                ["CardRuntime"] = "Tempo di esecuzione",
                ["RuntimeIdleDescription"] = "Il timer si avvia automaticamente dopo l'avvio.",
                ["LogsTitle"] = "Log di esecuzione",
                ["Checking"] = "Controllo in corso...",
                ["InstalledRunning"] = "Installato / In esecuzione",
                ["InstalledNotRunning"] = "Installato / Non in esecuzione",
                ["NotDetected"] = "Non rilevato",
                ["DetectedPathUnknown"] = "Rilevato, ma il percorso è sconosciuto.",
                ["ClashMissingDetail"] = "Clash non è stato trovato nei percorsi comuni, nei processi o nel registro.",
                ["ProxyReady"] = "Proxy pronto",
                ["ProxyReadySystemEnabled"] = "Proxy pronto / Proxy di sistema attivato",
                ["ProxyReadySystemDisabled"] = "Proxy pronto / Proxy di sistema disattivato",
                ["ProxyNotReady"] = "Proxy non pronto",
                ["SystemProxyEnabled"] = "Attivato",
                ["SystemProxyDisabled"] = "Disattivato",
                ["ProxyDetail"] = "Endpoint: {0}:{1} | Proxy di sistema: {2}",
                ["OpenClawMissingDetail"] = "OpenClaw non è stato trovato nel PATH o nelle posizioni npm comuni.",
                ["OpenClawPathDetail"] = "Percorso: {0}{1}",
                ["RuntimeUnknown"] = "In esecuzione (ora di avvio non disponibile)",
                ["RuntimeUnknownDetail"] = "Questo processo potrebbe non essere stato avviato da questo launcher.",
                ["RuntimeStartedAt"] = "Avviato alle: {0}",
                ["RuntimeLastRun"] = "Ultima esecuzione: {0}",
                ["RuntimeNotRunning"] = "Non in esecuzione",
                ["RuntimeStoppedDetail"] = "OpenClaw non è attualmente in esecuzione.",
                ["InfoTitle"] = "Informazioni",
                ["ErrorTitle"] = "Errore",
                ["ErrorPrefix"] = "[Errore] "
            },
            ["ja"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["WindowTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderTitle"] = "OpenClaw Desktop Launcher",
                ["HeaderSubtitle"] = "Clash（インストール済みの場合）と OpenClaw をワンクリックで起動し、OpenClaw をワンクリックで停止します。",
                ["LanguageLabel"] = "言語",
                ["CardClash"] = "Clash の状態",
                ["CardProxy"] = "プロキシの状態",
                ["CardOpenClaw"] = "OpenClaw の状態",
                ["ButtonStart"] = "OpenClaw を起動",
                ["ButtonStop"] = "OpenClaw を停止",
                ["HintBusy"] = "処理中です。しばらくお待ちください...",
                ["HintIdle"] = "開始ボタンは最初に Clash、その後 OpenClaw を確認します。OpenClaw が見つからない場合は公式ページを開きます。",
                ["CardAccess"] = "アクセス URL",
                ["AccessDescription"] = "OpenClaw の起動が確認されると、この URL が自動的にブラウザーで開きます。",
                ["CardRuntime"] = "稼働時間",
                ["RuntimeIdleDescription"] = "起動後、自動的にタイマーが開始されます。",
                ["LogsTitle"] = "実行ログ",
                ["Checking"] = "確認中...",
                ["InstalledRunning"] = "インストール済み / 実行中",
                ["InstalledNotRunning"] = "インストール済み / 停止中",
                ["NotDetected"] = "未検出",
                ["DetectedPathUnknown"] = "検出されましたが、パスは不明です。",
                ["ClashMissingDetail"] = "一般的なパス、プロセス、レジストリから Clash が見つかりませんでした。",
                ["ProxyReady"] = "プロキシ準備完了",
                ["ProxyReadySystemEnabled"] = "プロキシ準備完了 / システムプロキシ有効",
                ["ProxyReadySystemDisabled"] = "プロキシ準備完了 / システムプロキシ無効",
                ["ProxyNotReady"] = "プロキシ未準備",
                ["SystemProxyEnabled"] = "有効",
                ["SystemProxyDisabled"] = "無効",
                ["ProxyDetail"] = "接続先: {0}:{1} | システムプロキシ: {2}",
                ["OpenClawMissingDetail"] = "PATH または一般的な npm 配置から OpenClaw が見つかりませんでした。",
                ["OpenClawPathDetail"] = "パス: {0}{1}",
                ["RuntimeUnknown"] = "実行中（開始時刻は不明）",
                ["RuntimeUnknownDetail"] = "このプロセスはこのランチャーから起動されていない可能性があります。",
                ["RuntimeStartedAt"] = "開始時刻: {0}",
                ["RuntimeLastRun"] = "前回の稼働時間: {0}",
                ["RuntimeNotRunning"] = "停止中",
                ["RuntimeStoppedDetail"] = "OpenClaw は現在実行されていません。",
                ["InfoTitle"] = "情報",
                ["ErrorTitle"] = "エラー",
                ["ErrorPrefix"] = "[エラー] "
            }
        };
    }
}
